---
parser: 'babel-eslint'

env:
  node: true
  mocha: true
  es6: true

overrides:
  files: ["*.js"]
  excludedFiles: "tests/*"

rules:

  no-duplicate-imports: 2 # doesn't support flow imports.

  no-console: 0

  prefer-arrow-callback:
    - 0
    - allowNamedFunctions: false
      allowUnboundThis: false

  spaced-comment: 0
